[package]
name = "magic8ball"
version = "0.1.0"
edition = "2021"
authors = "Zian Smith"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
